# Generated by Django 2.0.7 on 2020-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nous_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=750),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
