# Generated by Django 2.0.7 on 2020-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nous_app', '0002_auto_20200428_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
